services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres

  composer:
    build: .
    entrypoint: composer
    command: validate
    volumes:
    - ./:/var/www
    depends_on:
      - db

  php:
    build: .
    entrypoint: php
    command: -v
    volumes:
      - ./:/var/www